//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/InteractionSample/InputActions/InteractionSampleInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InteractionSampleInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InteractionSampleInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InteractionSampleInputActions"",
    ""maps"": [
        {
            ""name"": ""Teleport"",
            ""id"": ""681b0566-8302-4264-9336-815af1405bab"",
            ""actions"": [
                {
                    ""name"": ""Trigger"",
                    ""type"": ""Button"",
                    ""id"": ""0e7759bc-8a59-427e-8523-08f610d2a2bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""509d90d2-bc5f-4155-8b67-0b49cb863f02"",
                    ""path"": ""<XRController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Teleport
        m_Teleport = asset.FindActionMap("Teleport", throwIfNotFound: true);
        m_Teleport_Trigger = m_Teleport.FindAction("Trigger", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Teleport
    private readonly InputActionMap m_Teleport;
    private ITeleportActions m_TeleportActionsCallbackInterface;
    private readonly InputAction m_Teleport_Trigger;
    public struct TeleportActions
    {
        private @InteractionSampleInputActions m_Wrapper;
        public TeleportActions(@InteractionSampleInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Trigger => m_Wrapper.m_Teleport_Trigger;
        public InputActionMap Get() { return m_Wrapper.m_Teleport; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TeleportActions set) { return set.Get(); }
        public void SetCallbacks(ITeleportActions instance)
        {
            if (m_Wrapper.m_TeleportActionsCallbackInterface != null)
            {
                @Trigger.started -= m_Wrapper.m_TeleportActionsCallbackInterface.OnTrigger;
                @Trigger.performed -= m_Wrapper.m_TeleportActionsCallbackInterface.OnTrigger;
                @Trigger.canceled -= m_Wrapper.m_TeleportActionsCallbackInterface.OnTrigger;
            }
            m_Wrapper.m_TeleportActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Trigger.started += instance.OnTrigger;
                @Trigger.performed += instance.OnTrigger;
                @Trigger.canceled += instance.OnTrigger;
            }
        }
    }
    public TeleportActions @Teleport => new TeleportActions(this);
    public interface ITeleportActions
    {
        void OnTrigger(InputAction.CallbackContext context);
    }
}
